Husan's solution
IT-forward/js-obj-meal-maker pull request #3
Opened 2020-12-26 13:50 UTC by Husan-Eshonqulov

Here I confirm that I:

- [ ] ran `yarn test` before pushing changes.
- [ ] wrote myself and understood all the code.
- [ ] checked cleanliness of my code after finishing the implementation.

2020-12-27 15:27 UTC, Husan-Eshonqulov commented
I have just looked at Oybek aka's code. It's almost the same as mine. 
I asked him for some help, but I didn't get his code.
Now, I am feeling like I copied.

2020-12-29 10:15 UTC, bahriddin requested changes
One comment and ready to go! 👍

2020-12-29 10:15 UTC, bahriddin commented on menu.js
> +    return this._courses[courseName][randomIndex];
You are calling `this._courses[courseName]` 2 times. I think making extra variable for its value is a good idea. Something like `courseDishes` should be fine.

2020-12-29 10:16 UTC, bahriddin commented
> I have just looked at Oybek aka's code. It's almost the same as mine.
> I asked him for some help, but I didn't get his code.
> Now, I am feeling like I copied 😔

If you can write as good as this after this task, mission is accomplished.

2020-12-29 12:23 UTC, Husan-Eshonqulov commented
> > I have just looked at Oybek aka's code. It's almost the same as mine.
> > I asked him for some help, but I didn't get his code.
> > Now, I am feeling like I copied 😔
> 
> If you can write as good as this after this task, mission is accomplished.

Ok

2020-12-29 13:26 UTC, bahriddin approved these changes

2020-12-29 13:27 UTC, closed without merging